# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EydpzEhmIRpiH93EL4MIaYQltUm6Royw
"""

!pip install memory_profiler matplotlib

import time
from memory_profiler import memory_usage
import matplotlib.pyplot as plt

def facto_i(n):
    res = 1
    for i in range(1, n + 1):
        res *= i
    return res

if __name__ == '__main__':
    n = int(input("ingrese un numero: "))

    inicio = time.time()
    mem_uso, resultado = memory_usage((facto_i, (n,)), retval=True, max_usage=True)
    fin = time.time()

    tiempo = fin - inicio

    print(f"factorial iterativo: {resultado}")
    print(f"tiempo: {tiempo:.6f} segundos")
    print(f"memoria usada: {mem_uso:.2f} MB")

    # gráfico
    plt.bar(["Iterativo"], [tiempo], color='blue')
    plt.ylabel("Tiempo (segundos)")
    plt.title("Tiempo de ejecución - Iterativo")
    plt.show()

    plt.bar(["Iterativo"], [mem_uso], color='green')
    plt.ylabel("Memoria (MB)")
    plt.title("Uso de memoria - Iterativo")
    plt.show()