# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EydpzEhmIRpiH93EL4MIaYQltUm6Royw
"""

!pip install memory_profiler matplotlib

import time
from memory_profiler import memory_usage
import matplotlib.pyplot as plt

def facto_r(n):
    if n <= 1:
        return 1
    return n * facto_r(n - 1)

if __name__ == '__main__':
    n = int(input("ingrese un numero: "))

    inicio = time.time()
    mem_uso, resultado = memory_usage((facto_r, (n,)), retval=True, max_usage=True)
    fin = time.time()

    tiempo = fin - inicio

    print(f"factorial recursivo: {resultado}")
    print(f"tiempo: {tiempo:.6f} segundos")
    print(f"memoria usada: {mem_uso:.2f} MB")

    # gráfico
    plt.bar(["Recursivo"], [tiempo], color='red')
    plt.ylabel("Tiempo (segundos)")
    plt.title("Tiempo de ejecución - Recursivo")
    plt.show()

    plt.bar(["Recursivo"], [mem_uso], color='orange')
    plt.ylabel("Memoria (MB)")
    plt.title("Uso de memoria - Recursivo")
    plt.show()